### ISSUE TITLE
centered whit background image

### ISSUE THREAD

**Issue by Jeramian** [BlackGekko/blackgekko.github.io#20]
it would be nice to have a white background banner for  the down pages, what do you think?

**Comment by Tyler-wood** [comment]
ok ill get on it

**Comment by Jeramian** [comment]
Thank you!

**Comment by Tyler-wood** [comment]
![gekkobanner](https://cloud.githubusercontent.com/assets/14165485/9915127/266ed056-5c6a-11e5-91d0-ef8ada4918b8.jpg)
